# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /blog/:categories/:year/:month/:day/:title/
relative_permalinks: true

# Setup
title:            Mohammadhussain Khatri
tagline:          'Android + Web Developer'
description:      'Software engineer and currently doing mobile apps developement with android.'
url:              ''
baseurl:          /

author:
  name:           'Mohammadhussain Khatri'
  url:            https://twitter.com/mohammadkhatri

paginate:         10
paginate_path: "/blog/page:num/"

github:
  profile:           https://github.com/mohammadkhatri


# Sass
sass:
  sass_dir: public/css/
  style: :compressed